### ISSUE TITLE
Error after import in a create-react-app project

### ISSUE THREAD

**Issue by milmaj** [strapi/strapi-sdk-javascript#12]
I import the library and get the following error:

`import Strapi from 'strapi-sdk-javascript';`

```
./node_modules/strapi-sdk-javascript/build/module/lib/sdk.js
Module parse failed: Unexpected token (14:12)
You may need an appropriate loader to handle this file type.
|             baseURL,
|             paramsSerializer: qs.stringify,
|             ...requestConfig
|         });
|         this.storeConfig = {
```

I have a simple create-react-app installation here.

**Comment by lucaperret** [comment]
Hi @milmaj, because this module isn't transpiled,
You should configure babel, for example with webpack:
```js
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('node_modules/strapi-sdk-javascript')
        ]
},
```

**Comment by milmaj** [comment]
Hi @lucaperret,

thx for your reply. I don't want to reject my react app. Maybe we'll find a solution in future.

Best, Milad

**Comment by lucaperret** [comment]
We'll probably export a UMD bundle soon...

**Comment by soupette** [comment]
@milmaj I got it working with create-react-app.
You can check the webpack config in this [boilerplate](https://github.com/strapi/strapi-examples/tree/update-boilerplate/create-react-app-sdk), it's not finished yet but the auth is working fine

**Comment by awerffeli** [comment]
Hi I had the same issue. This got it working:

1. Install Polyfill
`npm install --save-dev babel-polyfill`

2. In module.exports set entry:
`entry: ['babel-polyfill', './src/main.js'],`

3. In the webpack config under module add 
```
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          path.resolve('node_modules/strapi-sdk-javascript')
        ]
      }
```

You can see a working example using vuejs, strapi-sdk, webpack, babel here:
https://github.com/awerffeli/boilerplate-strapi-sdk-vue

**Comment by RyanDriscoll** [comment]
Hi @lucaperret 

I had a heck of a time trying to get webpack to transpile this sdk in a Gatsbyjs project. Gatsby abstracts away the webpack.config and gives you a 'modifyWebpackConfig' hook to make changes. I tried all of the above to no avail. I'm sure I'd figure it out eventually, but decided to just refactor your project to be promise based rather than use async/await, which did the trick. Would you consider releasing a transpiled version in the future?

Here's a gist showing the changes I made:
https://gist.github.com/RyanDriscoll/f54ef3d8eced423bd10ab5de2376dd7e

**Comment by albatrocity** [comment]
@milmaj @RyanDriscoll I got CRA (without ejecting) working with `strapi-sdk-javascript` by using [react-app-rewired](https://github.com/timarney/react-app-rewired) and [react-app-rewire-babel-loader](https://github.com/dashed/react-app-rewire-babel-loader) using the following `config-overrides.js`:

```js
const path = require("path");
const fs = require("fs");

const rewireBabelLoader = require("react-app-rewire-babel-loader");

const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

module.exports = function override(config, env) {
  config = rewireBabelLoader.include(
    config,
    resolveApp("node_modules/strapi-sdk-javascript")
  );
  return config;
};

```

**Comment by pierreburgy** [comment]
Did you try using `import Strapi from 'strapi-sdk-javascript/build/main'`?
