### ISSUE TITLE
vuejs webpack and the sdk

### ISSUE THREAD

**Issue by iojanis** [strapi/strapi-sdk-javascript#20]
**Informations**
- **Node.js version**: v8.11.2
- **npm version**: 5.6.0
- **Strapi version**: 12.5
- **Strapi-sdk-javascript version**: latest
- **Browser or Node.js**: Node.js

**What is the current behavior?**

 error  in ./node_modules/strapi-sdk-javascript/build/module/lib/sdk.js

Module parse failed: Unexpected token (14:12)
You may need an appropriate loader to handle this file type.
|             baseURL,
|             paramsSerializer: qs.stringify,
|             ...requestConfig
|         });
|         this.storeConfig = {

 @ ./node_modules/strapi-sdk-javascript/build/module/index.js 1:0-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

**Steps to reproduce the problem**

I just imported the sdk into my vue webpack sample application. 

**What is the expected behavior?**

**Suggested solutions**

**Confirm**
- [x] I'm sure that this issue hasn't already been referenced

**Comment by myWsq** [comment]
babel ignored 'node_modules'

**Comment by pierreburgy** [comment]
You can also [nuxt-typescript](https://www.npmjs.com/package/nuxt-typescript) but the solution above is simpler.
