### ISSUE TITLE
Get the total number of entries pertaining to the given filter criteria

### ISSUE THREAD

**Issue by Pritoj** [strapi/strapi-sdk-javascript#26]
**Is your feature request related to a problem? Please describe.**
Say you have a list. You only request 10 entries per request. However you also want the total number of entries present so you can create a load more or pagination functionality.

**Describe the solution you'd like**
A method which can be called with the given criteria to get this count. The API route is already present; all we need is the method.

**Describe alternatives you've considered**
I can call the API directly but it kinda defeats the purpose of the SDK I feel.

**Comment by lucaperret** [comment]
Fixed by #27
