### ISSUE TITLE
You may need an appropriate loader to handle this file type.importing strapi sdk

### ISSUE THREAD

**Issue by Assdi** [strapi/strapi-sdk-javascript#33]
getting this error while importing sdk file 
here is my question link 
[You may need an appropriate loader to handle this file type.importing strapi sdk](url)
please help

**Comment by lucaperret** [comment]
Should be reported in the core Strapi's repository please. https://github.com/strapi/strapi

**Comment by wil19558** [comment]
Had the exact same issue, fixed it by replacing the import:
https://github.com/strapi/strapi-sdk-javascript/issues/12#issuecomment-417171394
