### ISSUE TITLE
Auth In Headers

### ISSUE THREAD

**Issue by lajap** [strapi/strapi-sdk-javascript#36]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 6.4.1
- **Strapi version: 3.0.0-alpha**: 14.1.1
- **Strapi-sdk-javascript version**: latest
- **Browser or Node.js**: Node.js

**What is the current behavior?**
After a successful login or register, Strapi makes a successful request and get, with graphql enabled, content type with authenticated role. This content type needs authentication to bee accessed. But a refresh after login or register, Strapi Error: Forbidden on the backend and TypeError: Cannot read property 'forEach' of null from NUXT

I followed the Cooking a Deliveroo Clone Tutorials
https://blog.strapi.io/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-setup-part-1-7/

The tutorials failed to address non-public role. It seems request from nuxt to strapi has no authentication bearer [token] header on refresh, yet I have both jwt in sessionStorage on my browser and cookies.

**Confirm**
- [ ] I'm sure that this issue hasn't already been referenced

**Comment by lajap** [comment]
I think, I get the problem. Strapi JS SDK is written in TypeScript and later coverted to JS which requres axios, js-cookie, and qs. The sdk doesn't respect or sync or "whatever word that can best describe this" with the axios config in nuxt. Using nuxt axios alone works fine with strapi, at least for now. 

I use nuxt-auth, then axios including axios and graphql, but strapi js sdk is a headache for now. I'm using axios.

**Comment by pierreburgy** [comment]
This is weird but true: I tried to reproduce and had the same issue.

**Comment by lauriejim** [comment]
Hello @lajap , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue!

**Comment by leocb** [comment]
Has this issue been fixed? I'm still experiencing the same problem with the latest sdk version
