### ISSUE TITLE
Nuxt Server Error, statusCode: 500

### ISSUE THREAD

**Issue by odomojuli** [strapi/strapi-sdk-javascript#37]
**Informations**
- **node v10.8.0**:
- **npm 6.4.1**:
- **strapi 3.0.0-alpha.14.2**:
- **strapi-sdk-javascript@0.3.0**
- **Firefox 62.0.2 (64-bit)**
- **Chrome Version 69.0.3497.100 (Official Build) (64-bit)**

Following Deliveroo Tutorial.

`npm i strapi-sdk-javascript
`
```
  nuxt:render Rendering url / +3m
{ Error
    at Strapi.request (/Users/odomojuli/pro/client/node_modules/strapi-sdk-javascript/build/main/lib/sdk.js:59:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  statusCode: 500,
  message: 'Nuxt Server Error',
  name: 'NuxtServerError' }

```

Previous versions worked fine, can no longer replicate behavior.

**Confirm**
- [x] I'm sure that this issue hasn't already been referenced

**Comment by hamza-mostafa** [comment]
@lucaperret did you change the name of the model .. I had the same issue and after long search it appeared to be a wrong link in the index.vue cuz I changed the model

**Comment by anderson916** [comment]
same problem here.

**Comment by razza12** [comment]
This is most likely due to insufficient permission privileges on the content type for the public and authenticated roles (tick the find and findone boxes)

@odomojuli

**Comment by pierreburgy** [comment]
I agree, this is due to the permissions settings. I am closing the issue.

**Comment by odomojuli** [comment]
Changing the permission privileges did nothing for me.

**Comment by ALITHEALI** [comment]
Same @odomojuli ! Any Results? Actually I have tried it over and over, still the same issue! I assume it might be the use of graphql but I'm not sure. 

 I've got => 

```
✖ error Error
  at Strapi.request (/Users/ali/Desktop/monoc/client/node_mo
dules/strapi-sdk-javascript/build/main/lib/sdk.js:59:23)
  at process.internalTickCallback (internal/process/next_tic
k.js:77:7)
```

**Comment by robwil1966** [comment]
I am also following this tutorial and have hit the same problem. I've set full permissions on all user types and still have the same error. Any further ideas?

**Comment by robwil1966** [comment]
@odomojuli I managed to get the deliveroo clone working by editing index.vue ln:56 changing _id to id. I'm using mySQL not mongodb. The page now loads without error

**Comment by ccll** [comment]
@robwil1966 Thanks, that fixed my problem!

The stack trace error on the client page is far from useful in this case.
