### ISSUE TITLE
Ask for email confirmation before registering user

### ISSUE THREAD

**Issue by microcipcip** [strapi/strapi-sdk-javascript#43]
**Is your feature request related to a problem? Please describe.**
When I register a user, I'd like to check that the email exists before enabling it.

**Describe the solution you'd like**
Register the user without enabling it, extend API to enable it by sending a confirmation email.
```
await strapi.register(username, email, password, {confirmed: false})
```

**Comment by lauriejim** [comment]
This feature already exist.
You have to go in `Role & Permissions` > `Advanced` > `Enable email confirmation`

**Comment by tommygammon** [comment]
I'd like to implement email confirmation.

But it doesn't work
