### ISSUE TITLE
How to update many-to-many relation?

### ISSUE THREAD

**Issue by sgt-maddonut** [strapi/strapi-sdk-javascript#50]
There is `User` model that has `favorites` field, and `Product` model with `users` field, both models are related with many-to-many relation. When I try to update User's favorites, adding a new product to `favorites` field, it replaces all previous values there.

Code example:
```
const result = await strapi.updateEntry('users', userId, {
      favorites: productId
    });
```

What is the correct way to add value to relation field?

**Comment by lauriejim** [comment]
Did you check the documentation here ?
https://strapi.io/documentation/3.x.x/guides/models.html#relations

The value to send is the same as explain in the documentation.

**Comment by mdmundo** [comment]
https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#models
