### ISSUE TITLE
Latest build breaking project

### ISSUE THREAD

**Issue by abishekaditya** [strapi/strapi-sdk-javascript#87]
**Informations**
- **Node.js version**: v12.6.0
- **npm version**: 6.10.2
- **Strapi version**: 3.0.0-alpha.26.2
- **Strapi-sdk-javascript version**: ^0.3.1
- **Browser or Node.js**: node.js

**What is the current behavior?**

In my package.json I have my Strapi-sdk-javascript as ^0.3.1, It is breaking the build for my project. I think this has to do with your latest build failing

**Steps to reproduce the problem**

set strapi-sdk-javascript version as ^0.3.1 in package.json
deploy the application

**What is the expected behavior?**

It should not fail with `Cannot find module 'strapi-sdk-javascript'`

**Suggested solutions**

Possibly because of your broken 0.3.2 build which happened 16 hours ago

**Confirm**

- [x] I'm sure that this issue hasn't already been referenced

**Comment by jimmysafe** [comment]
I have the same issue, when deploying the build breaks and results in Cannot find module 'strapi-sdk-javascript'..

I have strapi-sdk-javascript@0.3.1

**Comment by lauriejim** [comment]
Hello! It was an issue during the publish on `npm` for the deprecation.
Can you check if it's good for you now.
Sorry for the inconvenience.

**Comment by abishekaditya** [comment]
Will check and let you know
