### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by lucaperret** [strapi/strapi-sdk-javascript#9]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
It would be nice to have [Greenkeeper](https://greenkeeper.io) activated on this repository:

  * Automatic, real time dependency updates
  * Runs your tests and alerts you when updates break your code
  * Convenient and flexible dependency update handling

**Comment by Aurelsicoko** [comment]
Done!
